# Site settings
title: Aaron Christian L. Quiamco CV
name: Aaron Christian L. Quiamco, ECT

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/aaronquiamco
 - title: LinkedIn
   url: https://www.linkedin.com/in/aaron-christian-q-b82019185/1

#Any buzzword skills you want to include
skills:
 - Hardware troubleshooting 
 - DevC++
 - VisualBasic.NET OOP
 - HTML
 - Familiar with Arduino and Raspberry Pi
 - MultiSim
 - Logisim
 - Proteus
 - AutoCad
 - Basic knowledge about PLC programming and SCADA systems
 - Familiar with Operating Systems (Windows and Linux)
 


#Work experience is required
roles:
 - title: Telecommuncations Department Intern
   start: 2018
   end: 2018
   employer: Jezka Construction Corporation
   description: CAD Operator in the Telecommunications Department, drafting surveyed tower sites. 
 - title: Technical Department Intern
   start: 2017
   end: 2017
   employer: ASERCO Sta. Rosa Branch
   description: Provided repair on various printing equipment and computer hardware.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2014
   subject: Electronics Engineering
   school: Polytechnic University of the Philippines






intro: |
  Fresh Graduate seeking a challenging career to gain an experience with a progressive organization that provides an opportunity to capitalize and enhance my technical skills & abilities in the field of Engineering and Information Technology.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
